use magasin;

INSERT INTO categories (version,nom, description) VALUES(0,'Boissons', 'Boissons non alcoolisées, cafés, thés, bières et ales');
INSERT INTO categories (version,nom, description) VALUES(0,'Condiments', 'Sauces sucrées et salées, relish, tartinades et assaisonnements');
INSERT INTO categories (version,nom, description) VALUES(0,'Confiseries', 'Desserts, bonbons et pains sucrés');
INSERT INTO categories (version,nom, description) VALUES(0,'Produits laitiers', 'Fromages');
INSERT INTO categories (version,nom, description) VALUES(0,'Céréales', 'Pains, crackers, pâtes et céréales');
INSERT INTO categories (version,nom, description) VALUES(0,'Viande/Volaille', 'Viandes préparées');
INSERT INTO categories (version,nom, description) VALUES(0,'Fruits et légumes', 'Fruits secs et tofu');
INSERT INTO categories (version,nom, description) VALUES(0,'Fruits de mer', 'Algues et poissons');

INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Exotic Liquid', '49 Gilbert St.', '(171) 555-2222');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'New Orleans Cajun Delights', 'P.O. Box 78934', '(100) 555-4822');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Grandma Kelly''s Homestead', '707 Oxford Rd.', '(313) 555-5735');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Tokyo Traders', '9-8 Sekimai Musashino-shi', '(03) 3555-5011');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Cooperativa de Quesos ''Las Cabras''', 'Calle del Rosal 4', '(98) 598 76 54');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Mayumi''s', '92 Setsuko Chuo-ku', '(06) 431-7877');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Pavlova, Ltd.', '74 Rose St. Moonie Ponds', '(03) 444-2343');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Specialty Biscuits, Ltd.', '29 King''s Way', '(161) 555-4448');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'PB Knäckebröd AB', 'Kaloadagatan 13', '031-987 65 43');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Refrescos Americanas LTDA', 'Av. das Americanas 12.890', '(11) 555 4640');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Heli Süßwaren GmbH & Co. KG', 'Tiergartenstraße 5', '(010) 9984510');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Plutzer Lebensmittelgroßmärkte AG', 'Bogenallee 51', '(069) 992755');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Nord-Ost-Fisch Handelsgesellschaft mbH', 'Frahmredder 112a', '(04721) 8713');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Formaggi Fortini s.r.l.', 'Dante, 75', '(0544) 60323');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Norske Meierier', 'Hatlevegen 5', '(0)2-953010');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Bigfoot Breweries', '3400 - 8th Avenue Suite 210', '(503) 555-9931');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Svensk Sjöföda AB', 'Brovallavägen 231', '08-123 45 67');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Aux joyeux ecclésiastiques', '203, Rue des Francs-Bourgeois', '(1) 03.83.00.68');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'New England Seafood Cannery', 'Order Processing Dept. 2100 Paul Revere Blvd.', '(617) 555-3267');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Leka Trading', '471 Serangoon Loop, Suite #402', '555-8787');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Lyngbysild', 'Lyngbysild Fiskebakken 10', '43844108');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Zaanse Snoepfabriek', 'Verkoop Rijnweg 22', '(12345) 1212');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Karkki Oy', 'Valtakatu 12', '(953) 10956');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'G''day, Mate', '170 Prince Edward Parade Hunter''s Hill', '(02) 555-5914');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Ma Maison', '2960 Rue St. Laurent', '(514) 555-9022');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Pasta Buttini s.r.l.', 'Via dei Gelsomini, 153', '(089) 6547665');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Escargots Nouveaux', '22, rue H. Voiron', '85.57.00.07');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Gai pâturage', 'Bat. B 3, rue des Alpes', '38.76.98.06');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Forêts d''érables', '148 rue Chasseur', '(514) 555-2955');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Savoie marché', '24, rue du Vercors', '06.20.44.32.43');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'Produit du nord', '42, rue Esquermoise', '(33) 03.20.56.32.45');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'British Food', '54, st Spirit', '(02) 444-2343');
INSERT INTO fournisseurs (version,nom, adresse, telephone)  VALUES(0,'MNS Distribution', '25, boulevard d''Ypres', '3222177149');

INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Thé Chais', 1, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chang', 1, 1, 19.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sirop d''anis', 1, 2, 10.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Assaisonnement Cajun de Chef Anton', 2, 2, 22.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mélange Gumbo de Chef Anton', 2, 2, 21.35);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Confiture de baies de Grandma', 3, 2, 25.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Poires séchées biologiques de l''Oncle Bob', 3, 7, 30.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sauce aux canneberges des Northwoods', 3, 2, 40.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mishi Kobe Niku', 4, 6, 97.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Ikura', 4, 8, 31.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Queso Cabrales', 5, 4, 21.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Queso Manchego La Pastora', 5, 4, 38.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Konbu', 6, 8, 6.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tofu', 6, 7, 23.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Genen Shouyu', 6, 2, 15.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pavlova', 7, 3, 17.45);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mouton Alice', 7, 6, 39.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tigres de Carnarvon', 7, 8, 62.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Biscuits au chocolat de l''heure du thé', 8, 3, 9.2);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Marmelade de Sir Rodney', 8, 3, 81.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Scones de Sir Rodney', 8, 3, 10.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pain croustillant de Gustaf', 9, 5, 21.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tunnbröd', 9, 5, 9.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Guaraná Fantástica', 10, 1, 4.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Crème de nougat NuNuCa', 11, 3, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bonbons Gumbär', 11, 3, 31.23);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chocolat Schoggi', 11, 3, 43.9);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Choucroute Rössle', 12, 7, 45.6);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Saucisse Thüringer Rostbratwurst', 12, 6, 123.79);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng Matjes Nord-Ost', 13, 8, 25.89);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Gorgonzola Telino', 14, 4, 12.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mascarpone Fabioli', 14, 4, 32.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Geitost', 15, 4, 2.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Sasquatch', 16, 1, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Steeleye Stout', 16, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng mariné Inlagd Sill', 17, 8, 19.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Saumon gravlax', 17, 8, 26.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Côte de Blaye', 18, 1, 263.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chartreuse verte', 18, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chair de crabe de Boston', 19, 8, 18.4);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chowder de palourdes de Jack', 19, 8, 9.65);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hokkien Fried Mee Singapourien', 20, 5, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Café d''Ipoh', 20, 1, 46.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Gula Malacca', 20, 2, 19.45);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng fumé', 21, 8, 9.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng salé', 21, 8, 12.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Biscuits Zaanse', 22, 3, 9.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chocolat', 22, 3, 12.75);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Maxilaku', 23, 3, 20.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chocolat blanc', 23, 3, 16.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pommes séchées de Manjimup', 24, 7, 53.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mélange Filo', 24, 5, 7.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pâtés de Perth', 24, 6, 32.8);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tourtière', 25, 6, 7.45);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pâté chinois', 25, 6, 24.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Gnocchi de nonna Alice', 26, 5, 38.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Ravioli Angelo', 26, 5, 19.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Escargots de Bourgogne', 27, 8, 13.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Raclette Courdavault', 28, 4, 55.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Camembert Pierrot', 28, 4, 34.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sirop d''érable', 29, 2, 28.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tarte au sucre', 29, 3, 49.3);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pâte à tartiner aux légumes', 7, 2, 43.9);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Semmelknödel de Wimmers', 12, 5, 33.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sauce piquante de Louisiane', 2, 2, 21.05);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Okra épicée de Louisiane', 2, 2, 17.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Laughing Lumberjack', 16, 1, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Biscuits écossais', 8, 3, 12.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Fromage Gudbrandsdalsost', 15, 4, 36.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Outback', 7, 1, 15.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Fløtemysost', 15, 4, 21.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mozzarella di Giovanni', 14, 4, 34.8);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Caviar rouge', 17, 8, 15.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tofu Longlife', 4, 7, 10.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Rhönbräu Klosterbier', 12, 1, 7.75);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Lakkalikööri', 23, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sauce verte originale de Francfort', 12, 2, 13.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Selecto', 33, 1, 10.2);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'El Mordjene', 33, 2, 12.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tango Bimo', 33, 3, 3.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mochi au thé vert', 6, 3, 3.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Doraki au haricot rouge', 6, 3, 9.95);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Miso Saikyo bio doux', 6, 7, 8.89);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Delifika', 9, 3, 29.9);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Thé Chais', 1, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chang', 1, 1, 19.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sirop d''anis', 1, 2, 10.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Assaisonnement Cajun de Chef Anton', 2, 2, 22.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mélange Gumbo de Chef Anton', 2, 2, 21.35);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Confiture de baies de Grandma', 3, 2, 25.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Poires séchées biologiques de l''Oncle Bob', 3, 7, 30.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sauce aux canneberges des Northwoods', 3, 2, 40.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mishi Kobe Niku', 4, 6, 97.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Ikura', 4, 8, 31.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Queso Cabrales', 5, 4, 21.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Queso Manchego La Pastora', 5, 4, 38.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Konbu', 6, 8, 6.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tofu', 6, 7, 23.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Genen Shouyu', 6, 2, 15.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pavlova', 7, 3, 17.45);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mouton Alice', 7, 6, 39.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tigres de Carnarvon', 7, 8, 62.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Biscuits au chocolat de l''heure du thé', 8, 3, 9.2);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Marmelade de Sir Rodney', 8, 3, 81.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Scones de Sir Rodney', 8, 3, 10.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pain croustillant de Gustaf', 9, 5, 21.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tunnbröd', 9, 5, 9.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Guaraná Fantástica', 10, 1, 4.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Crème de nougat NuNuCa', 11, 3, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bonbons Gumbär', 11, 3, 31.23);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chocolat Schoggi', 11, 3, 43.9);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Choucroute Rössle', 12, 7, 45.6);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Saucisse Thüringer Rostbratwurst', 12, 6, 123.79);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng Matjes Nord-Ost', 13, 8, 25.89);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Gorgonzola Telino', 14, 4, 12.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mascarpone Fabioli', 14, 4, 32.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Geitost', 15, 4, 2.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Sasquatch', 16, 1, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Steeleye Stout', 16, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng mariné Inlagd Sill', 17, 8, 19.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Saumon gravlax', 17, 8, 26.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Côte de Blaye', 18, 1, 263.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chartreuse verte', 18, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chair de crabe de Boston', 19, 8, 18.4);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chowder de palourdes de Jack', 19, 8, 9.65);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hokkien Fried Mee Singapourien', 20, 5, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Café d''Ipoh', 20, 1, 46.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Gula Malacca', 20, 2, 19.45);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng fumé', 21, 8, 9.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Hareng salé', 21, 8, 12.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Biscuits Zaanse', 22, 3, 9.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chocolat', 22, 3, 12.75);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Maxilaku', 23, 3, 20.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Chocolat blanc', 23, 3, 16.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pommes séchées de Manjimup', 24, 7, 53.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mélange Filo', 24, 5, 7.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pâtés de Perth', 24, 6, 32.8);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tourtière', 25, 6, 7.45);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pâté chinois', 25, 6, 24.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Gnocchi de nonna Alice', 26, 5, 38.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Ravioli Angelo', 26, 5, 19.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Escargots de Bourgogne', 27, 8, 13.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Raclette Courdavault', 28, 4, 55.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Camembert Pierrot', 28, 4, 34.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sirop d''érable', 29, 2, 28.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tarte au sucre', 29, 3, 49.3);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Pâte à tartiner aux légumes', 7, 2, 43.9);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Semmelknödel de Wimmers', 12, 5, 33.25);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sauce piquante de Louisiane', 2, 2, 21.05);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Okra épicée de Louisiane', 2, 2, 17.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Laughing Lumberjack', 16, 1, 14.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Biscuits écossais', 8, 3, 12.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Fromage Gudbrandsdalsost', 15, 4, 36.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Outback', 7, 1, 15.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Fløtemysost', 15, 4, 21.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mozzarella di Giovanni', 14, 4, 34.8);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Caviar rouge', 17, 8, 15.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tofu Longlife', 4, 7, 10.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Bière Rhönbräu Klosterbier', 12, 1, 7.75);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Lakkalikööri', 23, 1, 18.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Sauce verte originale de Francfort', 12, 2, 13.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Selecto', 33, 1, 10.2);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'El Mordjene', 33, 2, 12.0);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Tango Bimo', 33, 3, 3.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Mochi au thé vert', 6, 3, 3.5);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Doraki au haricot rouge', 6, 3, 9.95);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Miso Saikyo bio doux', 6, 7, 8.89);
INSERT INTO produits (version,nom, fournisseur_id, categorie_id, prix) VALUES(0,'Delifika', 9, 3, 29.9);

INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Maria', 'Anders', 'Obere Str. 57', '1967-11-02', 'maria.anders@gmail.com','$2a$10$BEEGSIzf57yo22urFzUCG.Aur29kf4uX2w0s6aFTg7uBggDhZKSEC');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Ana', ' Trujillo', 'Avda. de la Constitución 2222', '1955-04-12', 'atrujillo@yahoo.com', '$2a$10$ivvaLEjuG71BojVwhJIS9utOFjzZe2BgvmNAH463TRQyN44yfcTuO');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Antonio', 'Moreno', 'Mataderos 2312', '1971-04-23', 'amoreno@gmail.com', '$2a$10$Cs6TasY8cuTzTrnysKRTkO5kr8lCpfyVCfCM3arz.1gmY2nDxY3Tq');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Thomas', 'Hardy', '120 Hanover Sq.', '1971-01-15', 'thomas.hardy@gmail.com', '$2a$10$wIA741pwUX02W0vPF9SwMuJp.viHfLzWnjc5/vOfrN3VLWeAg27Nu');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Christina', 'Berglund', 'Berguvsvägen 8', '1968-02-15', 'berglund3@protonmail.com', '$2a$10$BvWxLqO5i4EZxai.h8MMuuXPuLk6606sss711LsYbh5L63k89p1d2');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Hanna', 'Moos', 'Forsterstr. 57', '1953-12-12', 'hanna.moos@yahoo.com', '$2a$10$BEEGSIzf57yo22urFzUCG.Aur29kf4uX2w0s6aFTg7uBggDhZKSEC');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Frédérique', 'Citeaux', '24, place Kléber', '1955-08-06', 'citeaux55@laposte.net', '$2a$10$bxlOrJgFO0Wy9TiucQf/XORhtnzZghSk6HPakTTFt2xyJ32CTTMRO');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Martín', 'Sommer', 'C/ Araquil, 67', '1963-04-29', 'sommer96@gmail.com', '$2a$10$ivvaLEjuG71BojVwhJIS9utOFjzZe2BgvmNAH463TRQyN44yfcTuO');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Laurence', 'Henriot', '12, rue des Bouchers', '1967-10-17', 'la.henriot@aol.com', '$2a$10$GFrKTv2ETC2cbunzWKB0qemHvMC/TPggK/Sj2rzOMO1TH87EnR/HG');
INSERT INTO utilisateurs (version,prenom, nom, adresse, date_naissance, email, password) VALUES(0,'Elizabeth', 'Lincoln', '23 Tsawassen Blvd.', '1973-02-03', 'lincoln23@aol.com', '$2a$10$glAuJqT237iJHryB5EyNLOOo.YuhUZRqZVfm/yM6sWpH/apEW.Y6C');

INSERT INTO commandes (version, user_id, date_commande) VALUES(0,2, '1996-09-18');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,3, '1996-11-27');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,4, '1996-12-16');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,4, '1996-11-15');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,5, '1996-12-16');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,5, '1996-08-12');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,5, '1996-08-14');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,7, '1996-07-25');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,7, '1997-02-05');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,7, '1996-09-04');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,7, '1996-11-22');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,8, '1996-10-10');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,9, '1996-11-25');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,9, '1996-10-29');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,9, '1996-10-16');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,10, '1997-01-10');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,10, '1997-01-10');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,10, '1996-12-20');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,10, '1997-01-30');
INSERT INTO commandes (version, user_id, date_commande) VALUES(0,10, '1996-08-26');

INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(1, 11);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(1, 42);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(1, 72);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(2, 14);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(2, 51);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(3, 41);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(3, 51);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(3, 65);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(4, 22);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(4, 57);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(4, 65);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(5, 20);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(5, 33);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(5, 60);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(6, 31);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(6, 39);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(6, 49);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(7, 24);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(7, 55);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(7, 74);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(8, 2);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(8, 16);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(8, 36);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(8, 59);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(9, 53);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(9, 77);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(10, 27);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(10, 39);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(10, 77);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(11, 2);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(11, 5);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(11, 32);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(12, 21);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(12, 37);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(12, 41);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(12, 57);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(12, 62);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(12, 70);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(13, 21);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(13, 35);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(13, 5);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(13, 7);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(13, 56);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(14, 16);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(14, 24);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(14, 30);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(14, 74);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(15, 2);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(15, 41);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(15, 17);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(15, 70);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(15, 12);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(16, 40);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(16, 59);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(16, 76);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(17, 29);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(17, 72);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(17, 33);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(17, 72);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(18, 36);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(18, 43);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(19, 33);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(20, 20);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(20, 31);
INSERT INTO produits_commandes (commandes_id, produits_id) VALUES(20, 72);
